### ISSUE TITLE
Link in README is dead

### ISSUE THREAD

**Issue by hofmannu** [fiji/HDF5_Vibez#20]
It seems the link in the README to the ETH library is dead? Googling resulted in https://unlimited.ethz.ch/display/JHDF/Download+Page but I am not sure if that page contains the same library so leaving it here as an issue.

**Comment by imagejan** [comment]
Here's the last snapshot of this page from the internet archive:

https://web.archive.org/web/20190605163957/https://wiki-bsse.ethz.ch/display/JHDF5

The link to the source code repository still seems to be valid:

https://sissource.ethz.ch/sispub/jhdf5

**Comment by mkitti** [comment]
The unlimited and sissource links are correct.

I'm working on a fork to move forward though:
https://github.com/JaneliaSciComp/janelia-jhdf5

**Comment by ctrueden** [comment]
@hofmannu Nothing like closing an issue with no explanation to motivate me as maintainer to finally address it!
